[package]
name = "shiina"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_bytes = "0.11.17"
sha1 = "0.10.6"
tokio = { version = "1", features = ["full"] }
